name: My Cool Workflow

on:
  push:
  pull_request:
  workflow_dispatch:
	
jobs:
    myfirstjob:
          name: firstjob
          runs-on: ubuntu-latest
          steps:
          - name: Step One
            uses: actions/checkout@v3
          - name: Step Two
            run: |
                	touch newfile.yaml
                  echo "Zoinks! Jinkies!" >> newfile.yaml
                  cat newfile.yaml
                  pwd
